{{- if and .Values.ingress.enabled .Values.ingress.gke .Values.ingress.gke.managedCertificate .Values.ingress.gke.managedCertificate.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}-managed-cert
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "optio.labels" . | nindent 4 }}
spec:
  domains:
    {{- range .Values.ingress.gke.managedCertificate.domains }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
